version: '3.4'

services:
  production-management-system:
    depends_on:
      - db
    build:
      context: .
      dockerfile: src/ProductionManagementSystem.WEB/Dockerfile
    image: protosevich2001/production-management-system
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=<password>
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ./https:/https
      - ./log.txt:/app/log.txt
      - ./uploads:/app/wwwroot/uploads
      - ./appsettings.json:/app/appsettings.json
    ports:
      - "32825:80"
      - "32824:443"
    restart: always

  db:
    image: mysql
    restart: 'always'
    volumes:
      - ./my-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: <root password>
      MYSQL_DATABASE: master
      MYSQL_USER: <username>
      MYSQL_PASSWORD: <user password>  
    ports:
      - "3306:3306"
        
  mysql-cron-backup:
    image: fradelg/mysql-cron-backup
    depends_on:
      - db
    volumes:
      - ./backup:/backup
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=<username>
      - MYSQL_PASS=<userpassword>
      - MAX_BACKUPS=15
      - INIT_BACKUP=0
      - CRON_TIME=0 7 * * *
    restart: unless-stopped
