version: '3.4'

services:
  productionmanagementsystem:
    image: ${DOCKER_REGISTRY-}productionmanagementsystem
    build:
      context: .
      dockerfile: Production management system/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123PassWord123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - "32825:80"
      - "32824:443"
    restart: always


  db:
    image: mysql:8
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123PassWord123
      MYSQL_DATABASE: new_schema
      MYSQL_USER: user1
      MYSQL_PASSWORD: 123Pass123
