version: '3.4'

services:
  production-management-system:
    depends_on:
      - db
    build:
      context: .
      dockerfile: src/ProductionManagementSystem.WEB/Dockerfile
    image: protosevich2001/production-management-system
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123PassWord123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - C:\https:/https
    ports:
      - "32825:80"
      - "32824:443"
    restart: always

#  production-management-system-api:
#    image: production-management-system-api
#    build:
#      context: .
#      dockerfile: ProductionManagementSystem.API/Dockerfile
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#      - ASPNETCORE_URLS=https://+:443;http://+:80
#      - ASPNETCORE_Kestrel__Certificates__Default__Password=123PassWord123
#      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
#    volumes:
#      - C:\https:/https
#    ports:
#      - "32827:80"
#      - "32826:443"
#    restart: always


  db:
    image: mysql
    restart: 'always'
    volumes:
      - ./my-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123Pass123
      MYSQL_DATABASE: master
      MYSQL_USER: user1
      MYSQL_PASSWORD: 123Pass123
    ports:
      - "3306:3306"
